apiVersion: v1
kind: Service
metadata:
  name: cs-server
  labels:
    app: cs-server
spec:
  clusterIP: 10.83.250.218
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32330
      port: 8070
      protocol: TCP
      targetPort: 8070
  selector:
    app: cs-server
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.224.178.24